version: "4.25.1"

services:
  server:
    build: .
    ports:
        - "8080:8080"
    depends_on:
      - mysql
    environment:
      JDBC_URL: jdbc:mysql://mysql:3306/todo
      JDBC_USER: root
      JDBC_PASS: root
      MYSQL_ROOT_PASSWORD: root

  mysql:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: root
      MYSQL_DATABASE: todo
    volumes:
      - "./mysql:/docker-entrypoint-initdb.d"

