version: "4.25"
services:
  servlet:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456789